version: "3.9"
services:
  server:
    image: fusion_test
    container_name: server
    ports:
      - "1234:1234"
    networks:
      - my_network

  client:
    image: fusion_test
    container_name: client
    depends_on:
      - server
    networks:
      - my_network

networks:
  my_network:
    driver: bridge